"""Add lock column

Revision ID: 684f2e4cbdc5
Revises: b882cb7b3464
Create Date: 2025-05-18 01:49:45.283764

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "684f2e4cbdc5"
down_revision: str | None = "b882cb7b3464"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.add_column(sa.Column("locked", sa.Boolean(), nullable=True, default=False))
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.execute("UPDATE games SET locked = 0")
        batch_op.alter_column("locked", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.drop_column("locked")

    # ### end Alembic commands ###
