"""Initial migration

Revision ID: b882cb7b3464
Revises:
Create Date: 2025-05-18 01:13:36.238962

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b882cb7b3464"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
