default_language_version:
  python: python3.12

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.5
  hooks:
  - id: ruff
    args: ["--config", "api/pyproject.toml", "--fix"]
  - id: ruff-format
    args: ["--config", "api/pyproject.toml"]

- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: ./api/run_mypy.sh
    language: system
    pass_filenames: false
    types: [python]
