name: API Check

on:
  push:
    paths:
      - 'api/**'

jobs:
  check-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache
            ~/.local
            ~/.poetry
          key: poetry-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: cd api && poetry install --no-root --with dev

      - name: Run full check
        run: make check-full
